// GENERATED by tools/art/nasa-bodies.mjs — do not edit by hand.
// Each sprite is a square PNG; discFrac is the body disc's diameter as a
// fraction of that square (rings and prominences spill past the disc).
export interface BodySprite {
  source: number;
  discFrac: number;
}

export const BODY_SPRITES = {
  sun: { source: require('../../assets/bodies/sun.png'), discFrac: 0.9615 },
  mercury: { source: require('../../assets/bodies/mercury.png'), discFrac: 0.9437 },
  venus: { source: require('../../assets/bodies/venus.png'), discFrac: 0.9433 },
  earth: { source: require('../../assets/bodies/earth.png'), discFrac: 0.9434 },
  moon: { source: require('../../assets/bodies/moon.png'), discFrac: 0.9435 },
  mars: { source: require('../../assets/bodies/mars.png'), discFrac: 0.9434 },
  jupiter: { source: require('../../assets/bodies/jupiter.png'), discFrac: 0.943 },
  saturn: { source: require('../../assets/bodies/saturn.png'), discFrac: 0.9258 },
  uranus: { source: require('../../assets/bodies/uranus.png'), discFrac: 0.9433 },
  neptune: { source: require('../../assets/bodies/neptune.png'), discFrac: 0.9433 },
  asteroid: { source: require('../../assets/bodies/asteroid.png'), discFrac: 0.9259 },
} as const;

export type SpriteId = keyof typeof BODY_SPRITES;
